[build]
  base = "apps/frontend"
  publish = "apps/frontend/.next"
  command = "cd ../.. && npm install && cd apps/frontend && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "https://alhussiny.netlify.app/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "apps/backend/src"
  node_bundler = "esbuild"
